### ISSUE TITLE
Inline AsciiMath isn't rendering when the "+" character is present in the same line

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#127]
In any environment, the inline math mode stops rendering when a new-line character ("+") is present.
[am-issue.zip](https://github.com/metanorma/metanorma-standoc/files/3679459/am-issue.zip)

**Comment by opoudjis** [comment]
Asciidoctor issue: *any* line with a stem macro in it and a break line, whether there are intervening characters or not, failed to be recognised as containing a stem macro, and is not passed on to stem processing. This is puzzling, because this does not happen in native Asciidoctor conversion to HTML; but presumably the native conversion does not do as much.

Asciidoctor is putting in a temporary placeholder in the string, with control characters, when it finds both a stem expression and a special character in a line: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb, line 1105. (I am using an earlier version of asciidoctor, but it does exactly the same thing). We are seeing the stem expression disappear, because asciidoctor is never going back and replacing that temporary character with the original stem expression.

It isn't going back, because I have in the meanwhile escaped these control characters as HTML entities. No, they shouldn't be doing things that way.

**Comment by opoudjis** [comment]
I feel dirty inside for this, but I'm now telling metanorma-standoc to unescape the control characters Asciidoctor uses to delimit temporary processing of substitutions, \u0096 and \u0097. metanorma-standoc escapes all the non ASCII characters it encounters as it goes, in the noko utility method, which generates to_xml output for the XML Builder output it encounters (as it should).  Lamentably, because of the Asciidoctor recursive processing method, that is premature.
