### ISSUE TITLE
Indentation for pseudocode formatting

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#129]
There is no indentation option for pseudocode formatting. Currently, all pseudocode lines are left-side aligned.

I attach sample file:
[pseudocode-sample.zip](https://github.com/metanorma/metanorma-standoc/files/3691082/pseudocode-sample.zip)

**Comment by opoudjis** [comment]
In those drafts, we simply did not mark up pseudocode at all.

We have pseudocode in NIST, and I'm going to see about whether I can port the solution from there. If so, I will need you @manuel489 to mark up the Pseudocode instances accordingly in your document.

**Comment by opoudjis** [comment]
I was hoping to do this with native Asciidoctor processing, but Asciidoctor is preemptively stripping initial spaces on lines, since that defines the lines to be preformatted. Any processing preserving the initial spaces of an Asciidoctor block, but not using preformatted rules, but processing Asciidoctor markup instead, will have to be a macro.

**Comment by opoudjis** [comment]
I have implemented this as a macro. This macro should replace the implementation of pseudocode as a role in NIST, and be propagated up to standoc, but I want us to test it out here first.

Ronald, I know we spoke of using code highlighting instead, but there's too much potential of idiosyncratic mischief here.

So the markup format will be:

````
[pseudocode]
====
*do in-parallel* +
  [smallcap]#SharedAccess# +
*enddo*

[smallcap]#ExclusiveAccess# ≡ +
  *if* _ag.mode_ = _exclusive_ ∧ ∀t ∊ [smallcap]#Token# : _t.available_ *then* +
    *do forall* _t_ : ∊  [smallcap]#_Token_# +
      _t.owner_ := _ag_ +
    *enddo* +
  *endif*
====
````

This macro preserves any line-initial spaces, and converts them into non-breaking spaces (and any initial tabs into four non-breaking spaces). Otherwise, text is processed as normal. Carriage returns will be treated as paragraphs, but the expected behaviour is to insert line breaks manually; this is not, after all, preformatted text at all.

@ronaldtse, need you to confirm you're ok with this approach, and then @manuel489 can update the markup. If approved, I will keep this ticket for when I get time to propagate it to standoc, and use it in NIST. (The macro should not break existing NIST documents.)

See attached sample.

[pseudocode-sample.zip](https://github.com/metanorma/metanorma-standoc/files/3728705/pseudocode-sample.zip)

**Comment by opoudjis** [comment]
Task will include documenting it in metanorma.com

**Comment by opoudjis** [comment]
Marking up as `figure/@class = "pseudocode"`. Semantically, this is properly sourcecode, not figure; but preventing inline markup in sourcecode is important enough to leave it alone.

**Comment by opoudjis** [comment]
To do:

* Merge in with NIST
* Create pseudocode and example/pseudocode styling in HTML CSS for all gems (but CSD?)
* Create pseudcode in Word CSS for all gems

**Comment by ronaldtse** [comment]
There’s no need to exclude csd, a general solution would work for all...

**Comment by opoudjis** [comment]
CSD was about the CSS. This issue is done, pending isodoc release to merge ITU in.
