### ISSUE TITLE
Allow including "List of Figures" and "List of Requirements"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#158]
From @rggibb:

> insert both a List of Figures and a List of Requirements after the Contents at the start of the document

This is useful for OGC, and probably some other flavors.

**Comment by opoudjis** [comment]
This is already implemented in OGC. (The issue does not belong in metanorma-standoc, as it is not a universal requirement across Metanorma.) metanorma-ogc is programmed to incorporate a list of figures, of tables, and of requirements/recommendations after the table of contents.

https://github.com/metanorma/mn-samples-ogc/blob/gh-pages/documents/17-069.doc for example (attached, updated last week) has a list of figures and of tables, and it only doesn't have a list of requirements because none were in the document. @rggibb, is this what you expect to see?

[17-069.doc.zip](https://github.com/metanorma/metanorma-standoc/files/3944649/17-069.doc.zip)

**Comment by opoudjis** [comment]
Move code to isodoc, enable optionally for ISO

**Comment by opoudjis** [comment]
This ticket is seeking to extend the functionality of Tables of figures, requirements, and tables beyond OGC, where they are mandatory.

It will be done as follows:

* Tables of figures, requirements, and tables shall be optional, requested by document attributes
* A placeholder for any one of these optional tables of contents shall be signalled by the inclusion in PresentationXML of the element `<toc type="table|figure|requirement"><title>...</title></toc>` within the misc-container, where `title` is the localised title of the type of table of contents.
* ToC are currently implemented only for Word and PDF.

**Comment by ronaldtse** [comment]
Yes this is very useful still. We would like to allow flavors (better yet, the user) to customise when this behavior is applied.
