### ISSUE TITLE
Content-based unique identifiers for elements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#24]
Currently element IDs are generated by random. A better approach is to use content-based hashing, which determines the ID of an element based on its content (and content's child content).

This way the generated XML files will only differ at the parts where they differ.

This is also the approach taken by Engyon (https://github.com/riboseinc/ros-engyon-syntax)

**Comment by opoudjis** [comment]
The most important requirement on an element ID is uniqueness. If two elements in a document have exactly the same content, then:

* If the ID is deterministically hashed based only on the element content, they will end up with the same ID. That is unacceptable.
* If the ID has a random component, then the generated XML file will no longer differ only at the part where the elements differ: the ID will be different each time anyway.
* If the ID is hashed based on the content plus the order of the element in the document, two instances of the same element with the same content still end up with different IDs. But the minute any content is interpolated, all the IDs after the interpolation will be different even if their content is the same.
* If the ID is hashed based on the content plus the clause number plus the order of the element within the clause, interpolations within the clause will still disrupt all IDs within the clause, but other parts of the document will be unaffected.

In addition, the identifiers used in crossreferences have to be persistent, so that crossreferences continue working even when the order of the crossreferenced element changes (let alone its content). Requiring all element identifiers to be digital signatures would break all crossreferences on the next update. 

This is a terrible idea, and I won't implement it as is, as it would break both the parsing and the crossreferencing of Metanorma. Yet again, you need to actually come up with a requirement for this, in order for it not to be a terrible idea.

* Is it digitally signing document elements, and detecting when they have changed? Then don't use the identifier, that's not what it's for, and an attempt to do this breaks what the identifier is for. Use a different attribute on the element (which I thought was what Engyon was doing.)
* Is it minimising the random changes in the document between changes, by not having a random component involved in ID generation? Then don't make the GUID-based identifiers based on digital signatures which can compromise uniqueness; a combination of clause number and element number within the clause, by itself and with no digital signature, is the most stable identifier you are likely to have.

**Comment by ronaldtse** [comment]
Sorry I've left this issue open for too long. For now, let's decouple the Engyon thought. This issue of unstable IDs has been raised by NIST.

You are absolutely correct that we don't want any randomness, and that the important thing is to have a "stable identifier", i.e.:

> Is it minimising the random changes in the document between changes, by not having a random component involved in ID generation?

Yes.

> Then don't make the GUID-based identifiers based on digital signatures which can compromise uniqueness; a combination of clause number and element number within the clause, by itself and with no digital signature, is the most stable identifier you are likely to have.

The combination of "clause number" and "element number" purely means an element's path to root, i.e. the path of  its parent to its parent to ... the root. This is the ID, and allows us to refer to an element like: "5.6.7.figure-1.note-2" or "6.7.8.list-2.a)".

The goal here is also to be able to extract out a particular element from the document, let's say the paragraph 2 of list item 3 of the 3rd list of clause 1.2.3".

We also need to specify the syntax for the ID. Any good ideas?

**Comment by opoudjis** [comment]
So you are agreeing with me?

If you are, the simplest solution is a hash of the actual XPath. Why reinvent the technology? If the structure changes, yes, the IDs change, but we would expect that.

So, your example would end up being a hash of `/iso-standard/clause[1]/clause[2]/clause[3]/ul[3]/li[3]/p[2]`. The SHA-1 of that is 1482897e53912467f561049151c51bbbba1f2bb4.

**Comment by ronaldtse** [comment]
Yes. 

1. Is there an understandable XPath for elements like "Figure" / "Note"?
2. Using the XPath means that you will need to keep track of the entire XPath of the node to the root for calculation every time? Will that be slow?
3. Do we want a hash as an ID? Or something more descriptive?
4. If I want to create a web service that returns a clause, but we want a user to be able express "clause 3.8 list item 3", can the user be able to do so without knowing XPath?

**Comment by opoudjis** [comment]
4. The  notion that the *user* should start counting items and addressing them thus, instead of using cross-references, is unacceptable. It introduces instability in referencing that is utterly counterproductive. The point of this is stable machine readable IDs, not to allow users to circumvent anchors altogethger.

**Comment by ronaldtse** [comment]
4. How else should a "user" refer to a clause?

The issue is that moving an element will already cause the IDs to change, and that in itself isn't ideal. (a content based ID will remain identical)

**Comment by opoudjis** [comment]
> How else should a "user" refer to a clause?

I am really not understanding this. They should be using cross-references and anchors. What is the problem with that?

You just said that your issue is the randomisation of IDs, but now you are saying you are trying to solve a different problem, addressing elements in a document without bothering to use user-defined anchors. And it is a solution that I see as encouraging the very worst problems that autonumbering was supposed to solve (that the internal structure of documents do change over time). 

Please articulate the requirement here better. What I understood in November was a terrible idea, and what I'm understanding now sounds even worse.

**Comment by ronaldtse** [comment]
> I am really not understanding this. They should be using cross-references and anchors. What is the problem with that?

A user needs to be able to fetch a certain element from the document via the web. This may or may not be related to remote cross-referencing.

> You just said that your issue is the randomisation of IDs, but now you are saying you are trying to solve a different problem, addressing elements in a document without bothering to use user-defined anchors. And it is a solution that I see as encouraging the very worst problems that autonumbering was supposed to solve (that the internal structure of documents do change over time).

Yes, the randomization of IDs is a problem. But addressing elements in a document is a related problem. Unless we're saying we separate these into two problems.

**Comment by opoudjis** [comment]
>> I am really not understanding this. They should be using cross-references and anchors. What is the problem with that?

> A user needs to be able to fetch a certain element from the document via the web. This may or may not be related to remote cross-referencing.

That isn't answering my question, but let me try and articulate your question better than you seem to be doing. :-/ 

The only reliable and persistent way of addressing an element of a Metanorma document is by assigning it an anchor. Whether the document is local or remote is irrelevant. 

In addition, Metanorma is set up so that every single block element has an anchor. However, if those anchors are not assigned, they are currently randomly generated.

If the user trying to reference the element cannot edit the document, they cannot make the anchor user-assigned; so any reference they generate will change with different versions of the document.

You are trying to come up with a general solution to this problem, that will work despite any changes to the document. That is of course impossible. If the anchor is generated based on the content of the block, and the block content is changed, then the anchor will change. If the anchor is generated based on the relative order of elements (xpath), and the elements are reordered or there is a deletion or addition along the path, then the anchor will change. And of the two options, I think order-based identifiers are going to be more stable than content-based identifiers: individual words will be changed more often than will entire blocks.

... Agreed?

**Comment by opoudjis** [comment]
This remains a bad idea, and I still don't see that it is well thought out. It also has not been a actioned for the past year, which means unless something changes, I'm not going to action it. I am unassigning myself.

**Comment by ronaldtse** [comment]
> If the ID is deterministically hashed based only on the element content, they will end up with the same ID. That is unacceptable.

A Unique ID must take into account of the context. A "unique ID" supposedly universally unique, like a UUID, is practically useless (because it cannot be unique).

The "true unique ID" of an element must be scoped to the top-level document.

> If the ID has a random component, then the generated XML file will no longer differ only at the part where the elements differ: the ID will be different each time anyway.

The ID should not have a random component.

> If the ID is hashed based on the content plus the order of the element in the document, two instances of the same element with the same content still end up with different IDs. But the minute any content is interpolated, all the IDs after the interpolation will be different even if their content is the same.

That is fine -- the scope of the Unique ID is only within the document itself, and is only accessed from the exterior as a function of the containing document. 

> If the ID is hashed based on the content plus the clause number plus the order of the element within the clause, interpolations within the clause will still disrupt all IDs within the clause, but other parts of the document will be unaffected.

Agree. The clause number should be part of the content.

**Comment by ronaldtse** [comment]
@opoudjis can you help document this algorithm somewhere in text? Thanks!
