### ISSUE TITLE
Double hyphen not getting rendered

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#263]
*Maybe this is a low-priority issue*

Escape markup `\--` to render double dash (instead of em-dash) isn't working.

*Sample markup:*
````
== Excerpt from _ISO-690_

Abbreviated key title is a specific title established by the ISSN network by replacing each 
significant word of a key title with the corresponding abbreviation from the List of Title 
Word Abbreviations  managed by the ISO 3297 for ISO 4. Abbreviations are based on ISO 4, 
Documentation\--Rules for the Abbreviation of Title Words and Titles of 
Publications and in accordance with the specific rules spelled out in the ISSN Manual.
````

*Metanorma:*
![capture](https://user-images.githubusercontent.com/33627611/80314159-d1ffea80-87bd-11ea-80b2-907b94e26d67.PNG)

*Asciidoctor:*
![capture2](https://user-images.githubusercontent.com/33627611/80314162-d4fadb00-87bd-11ea-96b8-2ca642f5d0bf.PNG)

**Comment by opoudjis** [comment]
The substitution is not going to be prevented by `\--`, since that `\` only has scope over a single character, and in any case the substitution is done by Asciidoctor with regexes.

The problem here is that that substitution is done by me, overriding Asciidoctor, also with regexes...

This is not the most elegant solution in the world, but: use `-&#x200c;-` . &#x200c; is the Zero Width Non Joiner, used in Unicode to prevent ligatures. It is invisible, and will also result in "--" not being recognised for replacement by em-dash.

I'll put this in metanorma.com as a tip.
