### ISSUE TITLE
break-up-urls-in-tables option should not affect XML/HTML/PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#269]
`:break-up-urls-in-tables:` option was introduced in https://github.com/metanorma/metanorma-standoc/issues/219 . However, this was only implemented to accommodate Word's broken table wrap, and should not affect the actual content of MN XML (and PDF and HTML).

Right now, even the HTML URLs are being cut, as can be seen by the number of reports (e.g. https://github.com/opengeospatial/ogc-metanorma-testing/issues/15)

I suggest that a proper solution is to embed this option in isodoc so that it only considers breaking URLs in Word, not making these URL changes in XML.

**Comment by opoudjis** [comment]
I dispute that it is not a problem for HTML; to make this Word-only is short-sighted. It is simply not true that a very long string in HTML will wrap, and that remains a problem. 

Given that the default is already off (so that they should *not* be adding the option anywhere after the latest release—the ticket is still confused about that), I don't think action is warranted.

**Comment by ronaldtse** [comment]
In HTML the proper wrapping mechanism is CSS “force-wrap”, which browsers implement, so breaking the URL is certainly the wrong thing to do there.

**Comment by opoudjis** [comment]
... And you're OK with PDF to be left to its own devices?

**Comment by opoudjis** [comment]
Welp.... I'm OK with PDF to be left to its own devices. Fine, localising to Word.
