### ISSUE TITLE
Nokogiri parse failure at fetching reference for 10303-45

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#274]
Initially I thought this is a Relaton bug but it isn't:
https://github.com/relaton/relaton-iso/issues/88

I actually don't get this on my local computer.

But this shows up for @CAMOBAP in the Docker container, and also this job:
https://github.com/metanorma/iso-10303/pull/36/checks?check_run_id=654004337

I suspect this may have to do with the size of the node insert again?

```
[relaton-iso] ("ISO 10303-45") found ISO 10303-45:1998
9751
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
9752
RuntimeError: error parsing fragment (1)
9753
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/node.rb:476:in `in_context'
9754
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/node.rb:476:in `parse'
9755
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/document_fragment.rb:19:in `initialize'
9756
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/document.rb:235:in `new'
9757
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/document.rb:235:in `fragment'
9758
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:354:in `<<'
9759
  /usr/local/bundle/gems/metanorma-standoc-1.3.26/lib/asciidoctor/standoc/section.rb:135:in `block in annex_parse'
9760
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:394:in `insert'
9761
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:377:in `method_missing'
9762
  /usr/local/bundle/gems/metanorma-standoc-1.3.26/lib/asciidoctor/standoc/section.rb:133:in `annex_parse'
9763
  /usr/local/bundle/gems/metanorma-iso-1.3.23/lib/asciidoctor/iso/section.rb:31:in `block in section'
9764
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:295:in `initialize'
9765
  /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `new'
9766
```

**Comment by opoudjis** [comment]
Of course, I'm going to have a devil of a time reproducing this, I can't rescue every instance of "<<", and Nokogiri is not saying anything about the crash anyway. But the error message is exactly the same as for the large Data-URI issue.

If the issue here is the size of the images, the fix in https://github.com/metanorma/metanorma-standoc/commit/cba1510801f1b19e6f1409c40a9380cc0114a565 happened on May 04; can you get @CAMOBAP to rerun using the github version of metanorma-standoc?

**Comment by ronaldtse** [comment]
Ping @CAMOBAP can you try with the git gem version for metanorma-standoc?

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis 

Because bundler doesn't work in Makefile for docker here is my steps

This is my steps to test:
 - `docker run -v $(pwd):/metanorma -it metanorma/metanorma /bin/bash`
 - `bundle add metanorma-standoc --git https://github.com/metanorma/metanorma-standoc`
 - `wget https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64 -O /usr/bin/yq`
 - `chmod +x /usr/bin/yq`
 - `make clean all`

The compilation was finished successfully but it took ~7-8min to process `Math OOXM` (I think it's not related to this issue

**Comment by opoudjis** [comment]
So... does that mean this issue is resolved?

**Comment by CAMOBAP** [comment]
@opoudjis I think yes
