### ISSUE TITLE
Metanorma "presentational XML" form

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#285]
We wish to create a "presentational XML" form of MN XML, which makes the current super-clean, semantic XML the "semantic XML".

(This aligns with the separation in MathML of semantic MathML vs presentational MathML)

The presentational XML is the "fully-expanded form", meaning that all logic has already been processed in this document.

The goal is to allow a user of presentational MN XML to be able to render the document in "dumb processors", i.e. those unable to execute rules to render labels (`Figure 1-3`, `Equation D.2-3`), to render the documents.

**Comment by opoudjis** [comment]
This ticket is going to take a year to implement as stated, so that's not how it's going to be.

This ticket will do only the following:

* Set up a presentational XML layer, as middleware between Metanorma XML and the outputs
* Populate all captions
* Populate all crossreferences to captions

**Comment by ronaldtse** [comment]
And the rest will go into other tickets.

**Comment by opoudjis** [comment]
It's unworkable to keep providing only the input XML as a parameter to the isodoc converters, given I will be introducing .presentation.xml as a file suffix; we are already dealing with that issue in XML RFC (https://github.com/metanorma/metanorma-ietf/issues/56). Am making explicit input file and output file parameters for isodoc.

**Comment by opoudjis** [comment]
Changes in Markup in the Presentation XML layer (for @Intelligent2013)

* STS and RFC will still be processed from the source XML layer, so the changes being made in Presentation XML are only for PDF (and HTML, DOC)
* There shall be no autonumbering in the Presentation XML layer: all captions and headings will contain their autonumber
* All `xref` tags will be populated with the required autonumbered reference.
* The formula label will now be contained in `//formula/name`.

**Comment by Intelligent2013** [comment]
> Changes in Markup in the Presentation XML layer (for @Intelligent2013)
> ...

@opoudjis I'm trying to generate a presentation XMLs, but looks like I do something wrong. For example, for `mn-samples-iso` I run:
```
make clean all
```
And in `documents` folder I see `....presentation.xml` but they are identical to `...xml`. For example:
rice-en.final.xml - 211161 bytes
rice-en.final.presentation.xml  - 211161 bytes.

```
fc /b rice-en.final.xml rice-en.final.presentation.xml
Comparing files rice-en.final.xml и RICE-EN.FINAL.PRESENTATION.XML
FC: no differences encountered
```

What did I do wrong and how can I obtain a presentation XMLs?

**Comment by opoudjis** [comment]
What you are doing is wrong is trying to do this two weeks too early. This is extremely difficult and painful refactoring of the entire stack of Metanorma, and I am working as fast as I can (50% overtime). 

1. I have published so that moving distinct content into the presentation XML is possible. I am still working on *actually* moving distinct content into the presentation XML. 
2. When I am ready for you to look at it, the code will be in a distinct code branch across all of Metanorma; and you will have to check out the same branch across all gems. That is why @CAMOBAP has been tasked with https://github.com/metanorma/metanorma-docker/issues/87, so that docker can take care of the branches for you.
