### ISSUE TITLE
Allow simple markup (" ") for inserting white space

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#336]
Currently, I've being inserting white spaces in math expressions by using: `"&#xA0;"`
However, normal AsciiDoc permits `" "` for that purpose, but not Metanorma apparently.

Example:
````
[stem]
++++
V_{"mes";m} (lambda) = 1 / {M(m)} {m V (lambda) + (1 - m) V'(lambda)}  " for "  0 <= m <= 1
++++
````

Output:

![Capture](https://user-images.githubusercontent.com/33627611/93409793-aca37400-f865-11ea-983c-e362f0c66511.PNG)

(Notice the "for" text.)

**Comment by opoudjis** [comment]
Recall that Asciidoctor is rendering Asciimath direct, whereas we are always converting it to MathML, and thence to Word's OOXML.

Investigating.

**Comment by opoudjis** [comment]
Spaces are being preserved in MathML: `<mtext> for </mtext>`. Because I have intervened in preprocessing for Word, converting spaces to nbsp, Word rendering respects those spaces. But MathJax in HTML does not. So I need to the same preprocessing for HTML rendering; I will just do it at the source level.
