### ISSUE TITLE
Asciidoctor > 2.0.10 drops certain parsed elements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#389]
From @CAMOBAP in https://github.com/metanorma/metanorma-cli/issues/189#issuecomment-736797913_

```
RFC XML: Line 000529:1672 IDREF "testtypes" without matching ID
RFC XML: Line 000560:2214 IDREF "testtypes" without matching ID
RFC XML: xref target testtypes does not exist in the document
RFC XML: xref target testtypes does not exist in the document
```

It "drops" some elements (sections, lists) causing the above errors.

The workaround is to lock `asciidoctor` gem to 2.0.10.

**Comment by ronaldtse** [comment]
@opoudjis believes this may be due to something else, he will investigate today.

**Comment by opoudjis** [comment]
There are two issues at play.

The first is that Metanorma expects a fixed structure of content under its Terms and Definitions sections, and will ignore content that does not fit it. Hence, elements disappearing if it thinks content belongs to Terms and Definitions when it does not.

The second is that Asciidoctor 2.0.11 has introduced a bug in its processing of lists at the end of included documents, which ends up swallowing the start of the following included file into that list. That means that the section heading of the section after the Terms section is being treated as part of the list; so a new section is not being opened; so all the content of that clause is being treated as part of the terms and definitions list, and elements are disappearing much more than before.

Because of this failure to parse lists in include files, we will need to freeze Asciidoctor at 2.0.10 until it is fixed.

I will also change the markup in the ACVP repository to avoid forcing Terms and Definitions formatting on sections so labelled, since their structure is clearly nothing to do with what Metanorma expects to see.

**Comment by opoudjis** [comment]
No, will need to propagate that includes need to have blank lines after them; this outcome is not regarded as a bug by Asciidoctor. Will write blog post.
