### ISSUE TITLE
On windows absolute path to an image gets still prefixes with `imagesdir` attribute

### ISSUE THREAD

**Issue by w00lf** [metanorma/metanorma-standoc#444]
Example: https://github.com/metanorma/metanorma-plugin-lutaml/pull/19/checks?check_run_id=2113304281
![image](https://user-images.githubusercontent.com/1158036/111200597-fe3d7900-85d2-11eb-9d31-06315a1a1f8d.png)

**Comment by opoudjis** [comment]
I've investigated this, and it is an issue with Asciidoctor, out of our control. Asciidoctor prefixes `imagesdir` to image URLs when they are not absolute addresses; but Asciidoctor explicitly refuses to consider `D:/` the beginning of an absolute address. Because it does not, it prefixes imagesdir before it. If at all possible, you should instead ensure that you prefix `file://` before any absolute links that go into images; and hopefully Windows Asciidoctor understands what they are. (You should confirm that on a PC.)
