### ISSUE TITLE
Type attribute not working for ordered lists

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#457]
Ordered lists show `alphabetic` letters regardless the specified type.

````
[type="arabic"]
. any use of such contribution by the contributor may not adversely affect the
promulgation and exploitation of the PAS by BSI; and
. a contributor continuing to use his or her own unique contributions may not
````

renders

![Capture2](https://user-images.githubusercontent.com/33627611/114632688-2d581080-9c8d-11eb-8e4d-e2ee3dca7a22.PNG)

**Comment by opoudjis** [comment]
If this relates to BSI, and this is the second list in a subclause, I've already addressed that as a flavour-specific rule: it will render with the metanorma-bsi gem. As you know, I am very reluctant to open the floodgates to arbitrary typing of sublists in Metanorma, because of the difficulties this introduces in Word, but in this instance (a) Word is not involved and (b) there is a strict rule realised for the standard anyway, so you don't even need to specify ordered list type.
