### ISSUE TITLE
Move citation rendering to presentation XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#479]
This was originally done in NIST: 
* metanorma/metanorma-nist#242

But other flavors are seeing the need for it now:
* metanorma/metanorma-ogc#218
* metanorma/metanorma-itu#261
* metanorma/metanorma-ribose#114

Perhaps there should be an ISO 690 gem (ping @andrew2net ).

**Comment by andrew2net** [comment]
> Perhaps there should be an ISO 690 gem (ping @andrew2net ).

@ronaldtse It seems we have it already https://github.com/metanorma/iso690render

**Comment by ronaldtse** [comment]
@andrew2net this gem metanorma/iso690render needs a refactor :wink:

**Comment by opoudjis** [comment]
There is semantic markup in ISO DIS Word, which needs to be made possible (https://github.com/metanorma/metanorma-iso/issues/595)

**Comment by opoudjis** [comment]
First step, now that relaton-render is refactored, is to overwrite the NIST invocation of references rendering in NIST Presentation XML with the output of relaton-render.

Then, back port relaton-render into isodoc, and then, overwrite its default, ISO 690 output with the configured out for the flavours given above.

**Comment by opoudjis** [comment]
@Intelligent2013 : henceforth, formattedref replaces the content of bibitem in Presentation XML, with three exceptions retained, which I believe to be necessary to process separately.

* docidentifier, to generate reference tags
* uri, in order to enable hyperlinking to be inserted into cross-references
* note, in order to enable footnotes to be inserted after the reference tag (which we process separately to the reference citation proper)
