### ISSUE TITLE
Empty normative references section is not being recognised

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#481]
BS 44001

**Comment by opoudjis** [comment]
In 44001, we have a different problem: the boilerplate for Normative References and Terms and Definitions is being added by Metanorma, on top of text already present in the document:

<img width="712" alt="Στιγμιότυπο 2021-06-17, 22 46 25" src="https://user-images.githubusercontent.com/1911039/122399230-f1f3fe00-cfbd-11eb-9291-95cf6187cf23.png">

````
[bibliography]
== Normative references

There are no normative references in this document.

== Terms and definitions

For the purposes of this document, the following terms and definitions apply.

ISO and IEC maintain terminological databases for use in standardization at the following addresses:

* ISO Online browsing platform: available at http://www.iso.org/obp[http://www.iso.org/obp]

* IEC Electropedia: available at http://www.electropedia.org/[http://www.electropedia.org/]
````

The solution for this is either to leave out the boilerplate during conversion from STS, or else to tell Metanorma not to add its own boilerplate on top of the boilerplate already supplied:

https://www.metanorma.org/author/topics/document-format/section-terms/#overriding-predefined-text
https://www.metanorma.org/author/topics/document-format/bibliography/#predefined-text

````
[bibliography]
== Normative references

[NOTE,type=boilerplate]
--
There are no normative references in this document.
--

== Terms and definitions

[.boilerplate]
=== My predefined text

For the purposes of this document, the following terms and definitions apply.

ISO and IEC maintain terminological databases for use in standardization at the following addresses:

* ISO Online browsing platform: available at http://www.iso.org/obp[http://www.iso.org/obp]

* IEC Electropedia: available at http://www.electropedia.org/[http://www.electropedia.org/]
````

@Intelligent2013 Can you strip boilerplate that matches the ISO default? If not, do the latter.

**Comment by Intelligent2013** [comment]
@opoudjis ok, I'll check all STS xml examples about boilerplate's texts and if they all match the ISO default, then xslt will remove it, or will add `[.boilerplate]`.

**Comment by Intelligent2013** [comment]
Regarding 'Normative References', in the STS xml samples there are 9 different texts:
1. `<p>There are no normative references in this document.</p>`
adoptions\bs-en-iso-56000
adoptions\bs-en-iso-56003
adoptions\bs-iso-44001
bs-codes-of-practice\bs-7858


2. `<p>There are no normative references in this British <named-content content-type="term" xlink:href="#term_3.26">Standard</named-content>.</p>`
standards\bs-202000


3. `<p>The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>`
adoptions\bs-en-12973
adoptions\bs-en-iso-56002
adoptions\bs-iso-30042
adoptions\bs-iso-44002
adoptions\bs-iso-44003
adoptions\bsi-iso-30042
adoptions\iso-10667-1
adoptions\iso-10667-2
adoptions\pd-iso-tr-44000


4. `<p>The following Recommendations and International Standards contain provisions which, through reference in this text, constitute provisions of this Recommendation | International Standard. At the time of publication, the editions indicated were valid. All Recommendations and Standards are subject to revision, and parties to agreements based on this Recommendation | International Standard are encouraged to investigate the possibility of applying the most recent edition of the Recommendations and Standards listed below. Members of IEC and ISO maintain registers of currently valid International Standards. The Telecommunication Standardization Bureau of the ITU maintains a list of currently valid ITU-T Recommendations.</p>`
adoptions\isoiec-29151


5. `<p>The following referenced documents are indispensable for the application of this standard. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced standard (including any amendments) applies.</p>`
bs-codes-of-practice\bs-7273-4-2015-A1-2021


6. `<p>The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>`
bs-design-requirements\bs-4592-0-A1-2012
bs-design-requirements\bs-8887-1-2006
bs-guides\bs-11000-2
bs-guides\bs-7000-2
bs-specification\bs-8887-220
bs-terms\bs-8887-2009

7. `<p>The following documents, in whole or in part, are normatively referenced in this document and are indispensable for its application. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>`
bs-guides\bs-7000-4
bs-methods-of-specifying\bs-8500-1-2015-A2-2019
bs-methods-of-specifying\bs-8500-2-2015-A2-2019
bs-specification\bs-8654-2015


8. `<p>References, which form part of the retrofit standards framework, are listed in Clause <xref ref-type="sec" rid="sec_16"><bold>16</bold></xref>.</p>`
`<p>Of the documents listed in Clause <xref ref-type="sec" rid="sec_16"><bold>16</bold></xref>, the following references are central to the application of this PAS. They are referred to in the text in such a way that some or all of their content constitutes provisions of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>`
pas\pas-2030\

9. `<p>The following documents, in whole or in part, are normatively referenced in this document and are indispensable for its application. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any <named-content content-type="term" xlink:href="#term_3.1">amendments</named-content>) applies.<sup><xref ref-type="fn" rid="fn_1"><sup>1)</sup></xref></sup></p>`
standards\bs-0

Because predefined text specific to the Metanorma flavour, but sts2mn doesn't , then it would be better to enclose text for Normative References in `[NOTE,type=boilerplate]`.

**Comment by Intelligent2013** [comment]
For section Terms also added
```
[.boilerplate]
=== My predefined text
```
and
```
[.boilerplate]
=== blank}
```

All done.
