### ISSUE TITLE
Handling references to "global document identifiers" not defined in bibliographic entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#547]
ISOSTS documents sometimes have text like this:

```xml
<p>The following terms, used in this edition of 
<std std-id="iso:std:iso:13485:en" type="undated"><std-ref>ISO 13485</std-ref></std>
to describe the supply chain, have been changed to reflect the vocabulary currently used:</p>
```

Here the `iso:std:iso:13485:en` is an ISO URN defined in RFC 5141.

We need to deal with round-tripping. How do we deal with them?

**Comment by opoudjis** [comment]
Clearly std-ref is the ISO canonical identifier, so `std/std-ref` becomes `<docidentifier type="ISO">`, and `std/@std-id` becomes `<docidentifier type="ISO-URN">`; we add the latter to any bibitems on converting the document into Metanorma XML, and use that docidentifier for round-tripping.

... Can I close this ticket, or assign it to @Intelligent2013?

**Comment by ronaldtse** [comment]
@opoudjis do you mean we already have a mechanism to do this (link content to a ISO URN reference without defining in the bibliography) in Metanorma AsciiDoc?

**Comment by opoudjis** [comment]
No, I just meant that if we inject that URN into the bibitem on conversion to Metanorma XML, we can do round tripping. If we're converting into Asciidoc, we can't do that right now, but it seems to me these URNs should be predictable, so they can be inserted by Relaton anyway. 

I am not sure I understand what you are trying to do here though...

**Comment by opoudjis** [comment]
No, that is unnecessary, and frankly, voodoo. We are not going to dumb down our rigorous bibliographical practice just because ISO STS does.

The real solution is to include the reference and then hide it in the bibliography, something already implemented:

````
<<iso13485>>

...

[bibliography]
== Bibliography
* [[[iso13485,hidden(ISO 13485)]]]
````

Alex Dyuzhev has already been hiding bibliographic entries a lot.

Looking up the ISO URN would be an issue whether the bibliographic reference is shown in the bibliography or not, and remains a Relaton issue.

**Comment by ronaldtse** [comment]
@opoudjis I'm not convinced this is voodoo -- a link of "urn:iso:xxx" is by nature just like a link of "https://xxx". This is not voodoo also because this item does not appear in the bibliography. I feel that sometimes we are given a hammer and we treat everything as a nail. But maybe this is a different kind of nail...

We need to distinguish what is a bibliographic item vs what is a simple link.

**Comment by opoudjis** [comment]
Links are HTTP URI. DOIs are HTTP URIs. Handles, URNs, ARKs, and all the other schemes that avoid HTTP but seek to be identifiers are not inherently resolvable, and are therefore no different than ISO native identifiers like ISO 13485. Without a resolver service, they are just document identifiers, and the way we make sense of document identifiers is with. our. hammer.

If you want `link:std-ref[ISO 13485]`, I'm simply going to implement it as `<<iso13485>>`, and hide ISO 13485 in the bibliography. There is no reason for me to do otherwise: the link still needs to look up where ISO 13485 is, find out what ISO 13485 is for the semantics of the document, and pass its online location on to Presentation XML, to generate a hyperlink.

And if you want `link:standard-urn[iso:std:iso:13485:en]`, you're going to have to get Relaton to build a URN resolver to work out that this is ISO 13485, and I will still need to go through the foregoing steps to work out where to hyperlink to.

If there *is* a standards URN resolver out there, I can just jam the URN into it, just as we would do with DOIs and dx.doi.org. Short of that, we already have a resolver infrastructure for standards identifiers, and it is nuts to sidestep it. The link:std-ref you're proposing is just syntactic sugar.

**Comment by ronaldtse** [comment]
> And if you want link:standard-urn[iso:std:iso:13485:en], you're going to have to get Relaton to build a URN resolver to work out that this is ISO 13485, and I will still need to go through the foregoing steps to work out where to hyperlink to.

Relaton already has a URN resolver to the ISO website. However, not ALL ISO URNs are resolvable. There may or may not be a hyperlink.

**Comment by opoudjis** [comment]
Proceeding with syntactic sugar implementation:

````
<<anchor,localities,text>>

[bibliography]
* [[[anchor,hidden(ID)]]]
````

is equivalent to

````
std-link:[ID,localities,text]
````

Once Relaton can fetch documents by URN, std-link will process them as well. I don't see the need to have two distinct macros, the URN should be identifiable, and if it isn't, we can just prefix it with `URN`.

**Comment by opoudjis** [comment]
> > And if you want link:standard-urn[iso:std:iso:13485:en], you're going to have to get Relaton to build a URN resolver to work out that this is ISO 13485, and I will still need to go through the foregoing steps to work out where to hyperlink to.
> 
> Relaton already has a URN resolver to the ISO website. However, not ALL ISO URNs are resolvable. There may or may not be a hyperlink.

If there isn't a hyperlink, then we don't render a hyperlink. Oh well. Doesn't impact the implementation.

**Comment by opoudjis** [comment]
We are not doing `link:standard-urn[]` for now; once URN resolution is enabled, I will work out how to differentiate URN rendering, if that is even necessary. Right now, URNs do not resolve, but they will be passed on as document identifiers, so `link-std:[URN]` will in fact render as `URN`.

Hyperlink to bibliography entry needs to be suppressed in isodoc, since there is no bibliographic entry any more. If there is a URL fetched, that still needs to be accessed.

**Comment by ronaldtse** [comment]
> URN resolution is enabled

I don't know when or if that will happen... Let's see.
