### ISSUE TITLE
Extract this caching bit to Relaton gem?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#62]
https://github.com/metanorma/metanorma-standoc/blob/f5cfc0126213e43712cbb2512b28b10ec6f8486d/lib/asciidoctor/standoc/base.rb#L108

@opoudjis should we extract this caching bit to the Relaton gem?

If so then we can utilize the Relaton cache here too (https://github.com/ISO-TC211/geolexica.com/issues/31).

**Comment by ronaldtse** [comment]
Bits to extract are:

https://github.com/metanorma/metanorma-standoc/blob/f5cfc0126213e43712cbb2512b28b10ec6f8486d/lib/asciidoctor/standoc/base.rb#L108-L118


And

https://github.com/metanorma/metanorma-standoc/blob/5317d381d493609ee4ef319a0032b9cc980fb56a/lib/asciidoctor/standoc/ref.rb#L197-L205

**Comment by opoudjis** [comment]
... Do you really want to pass five different asciidoctor document attributes on to relaton? (no-isobib-cache, no_isobib, local-cache, local-cache-only, flush-caches)

Really?

Even if I bundle them into a hash, I don't think this should reside inside of relaton. I think they are Metanorma-specific criteria.

The functions global_bibliocache and local_bibliocache_name could be passed to relaton, but that woild also be a mistake, because you would take away the ability to customise them in other gems.

I think both proposed refactorings take away necessary flexibility.

**Comment by ronaldtse** [comment]
Well, the thing is since I have to use Relaton in the other site without Metanorma, I either port the caching functionality over or reimplement it in Relaton.

**Comment by opoudjis** [comment]
Fine, I'll port it. I will not work on it soon unless you ask me; I want to turn to OGC now.

**Comment by opoudjis** [comment]
The port is cleaned up: 

````
    # Initialise and return relaton instance, with local and global cache names
    # local_cache: local cache name; none created if nil
    # global_cache: boolean to create global_cache
    # flush_caches: flush caches
Relaton::DbCache::init_bib_cache(opts)
````

**Comment by ronaldtse** [comment]
@opoudjis can we specify the path to create the DB (as a local cache)? Is that the “local cache name”?

**Comment by opoudjis** [comment]
The local cache name is ultimately passed as an argument to "FileUtils::mkdir_p". So it can be a relative path, relative to the working directory of the invoking routine, or an absolute path.

**Comment by ronaldtse** [comment]
I think we can have a default and also a specialized value.
