### ISSUE TITLE
Crash specific to GHA rubygems for Ruby 3.0

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#620]
Sorry i can't understand what is going wrong, but it has now occurred twice.

https://github.com/metanorma/metanorma-standoc/runs/6007800343?check_suite_focus=true

**Comment by opoudjis** [comment]
Also turning up in

https://github.com/metanorma/isodoc/runs/6008906851?check_suite_focus=true

**Comment by CAMOBAP** [comment]
looks like broken damaged version of gems was cached, looking for some way to drop the cache without workflow change

**Comment by ronaldtse** [comment]
Is this because of https://github.com/metanorma/emf2svg-ruby/issues/28 ?

**Comment by CAMOBAP** [comment]
> Is this because of [metanorma/emf2svg-ruby#28](https://github.com/metanorma/emf2svg-ruby/issues/28) ?

I don't think so, btw cache invalidation doesn't help

There are https://github.com/rubygems/rubygems/issues/5161 and https://github.com/rubygems/rubygems/issues/5160 (which is fixed, I will check ruby/ruby-setup if it updates rubygems

**Comment by CAMOBAP** [comment]
Issue happens for 3.0.4, but it doesn't exists on 3.0.3, checking https://github.com/ruby/setup-ruby/issues

**Comment by CAMOBAP** [comment]
Also, I have found out that removing [the first two encoding lines](https://github.com/metanorma/metanorma-standoc/blob/main/Gemfile#L1-L2) fixes the problem, but this is definitely not a solution which we want

Investigation in progress

**Comment by CAMOBAP** [comment]
Proposed if is https://github.com/metanorma/metanorma-build-scripts/commit/5729cc66296f4c3deb2f6ff5f66c6cfe104bb754

I know that we have the same issue for `isodoc` and probably for other repos too, so I will update other workflows too (luckily now we can do it in a single place)

@ronaldtse @opoudjis any thoughts on the solution?
*I didn't applied this for all ruby version just because this may have negative impact on cache, also probably mostly users don't upgrade `rubygems` correct me if I'm wrong

**Comment by ronaldtse** [comment]
> probably mostly users don't upgrade rubygems correct me if I'm wrong

I'm sure people don't upgrade rubygems directly, and we're trying to make people use the packed-mn or Docker version.

**Comment by opoudjis** [comment]
This is now blocking release, none of the gems are passing, including metanorma-docker.

**Comment by ronaldtse** [comment]
Merged that PR. Thanks! Hope it works now.
