### ISSUE TITLE
Inline specification of alternative fonts/languages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#647]
We need a way to indicate that what characters are to be represented by what fonts, in the case where special fonts are needed.

As suggested by @intelligent2013, to indicate font for the individual part of the text, I think we can introduce new construction:
```
... text [font 'Noto Sans JP']#ABC# text... 
```

Metanorma XML:
```xml
... text <inline font-family="Noto Sans JP">ABC</inline> text ...
```

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-native-pdf/issues/368#issuecomment-1147523786_

**Comment by opoudjis** [comment]
I have just defined `s:category[]` for semantically defined spans, but I don't mind segregating semantic microformatting from rendering microformatting (and `[format]#x#` has stronger associations with the latter, because of its use to generate CSS.)

But I'm not hard-coding idiosyncratic attributes like "font-family". We may not support open-ended CSS, but I'm going to have the contents of this tag element be explicit CSS. So, `[css font-family:"Noto Sans JP"]#xxx#`.

**Comment by opoudjis** [comment]
I'm also not making up a brand new element. This shall be `<span style=...>`.
