### ISSUE TITLE
Add 'formula' and 'equation' designation's types

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#686]
Source issues: https://github.com/metanorma/mnconvert/issues/230, https://github.com/metanorma/mnconvert/issues/190
Currently Metanorma supports these designation's types (https://www.metanorma.org/author/topics/document-format/section-terms/#metadata):

> `type`
>
>  type of expression used as designation; supported values are
>
> - `prefix`
> - `suffix`
> - `abbreviation`
> - `full`

In [Guidelines for coding IEC and ISO standards in NISOSTS.pdf](https://github.com/metanorma/mnconvert/files/9429314/Guidelines.for.coding.IEC.and.ISO.standards.in.NISOSTS.pdf) (page 73) determines additionally these 'forms of the term':
- formula
- equation

Need support them in Metanorma.

**Comment by opoudjis** [comment]
We do support them, but not there.

https://www.metanorma.org/author/topics/document-format/section-terms/#metadata is describing verbal designations. The UML grammar says that explictly: "Type of linguistic form used as designation."

Equations are NOT verbal designations, and they are covered under

https://www.metanorma.org/author/topics/document-format/section-terms/#non-verbal-designations-representations

> A figure or formula can be used instead of a verbal expression, provided it immediately follows a blank designation, before any metadata definition list.

In the Metanorma Semantic XML grammar, these are:

````
Designation =
  attribute absent { xsd:boolean }?,
  attribute geographic-area { text }?,
  (expression_designation | letter_symbol_designation | graphical_symbol_designation ),
  fieldofapplication?, usageinfo?,
  termsource*

expression_designation =
  element expression {
    ## ISO-639
    attribute language { text }?,
    ## ISO-15924
    attribute script { text }?,
    attribute type { ExpressionDesignationType }?,
    attribute isInternational { xsd:boolean }?,
    element name { (PureTextElement|stem|index)* },
    element abbreviation-type { AbbreviationType }?,
    element pronunciation { LocalizedString }?,
    element grammar { Grammar }?
  }  

letter_symbol_designation =
  element letter-symbol {
    attribute isInternational { xsd:boolean }?,
    element name { (PureTextElement | stem)+ }
  }
````

Formulas and equations are expected to be found under `letter-symbol`.

We are not differentiating symbol, formula, equation in Metanorma, because the specs we looked at do not make that distinction. 

TBX proper itself currently restricts termType, according to https://github.com/LTAC-Global/TBX_basic_module/releases/latest/download/Basic_Module_Definition.pdf

````
* fullForm
* acronym
* abbreviation
* shortForm
* variant
* phrase
````

The differentiation in your document comes not from TBX, but from ISO's modification of TBX, https://www.iso.org/schema/nisosts/v0.2/doc/tbx/index.html , which asserts that the values are:

````
(acronym | abbreviation | fullForm | symbol | variant | formula | equation)
````

For ISO, of all bodies, to be forking a standard to meet its own needs, instead of getting the source standard changed, is appalling. It may be that an earlier version of TBX had this distinction; it's hard to tell, and TBX's site is extremely hard to navigate. (Everything ends up sending the user to a PDF anyway.)

I need confirmation from @ronaldtse before I add a type to letter-symbol, encompassing symbol, formula, equation. I can do it, but I don't have confidence that this list of types is authoritative, when it comes from a forked standard to begin with.

**Comment by ronaldtse** [comment]
I'm not entirely sure why ISO differentiates formula and equation, but I confirm that we can add them as designation types.

My question is why add to `letter_symbol_designation` because it contains this:
```
letter_symbol_designation =
  element letter-symbol {
    attribute isInternational { xsd:boolean }?,
    element name { (PureTextElement | stem)+ }
  }
```

The equation or formula does not need `isInternational`, so if we add it there it could be inappropriate.

**Comment by opoudjis** [comment]
> `letter-symbol`:: the designation is not a linguistic expression, but a letter,
symbol, formula, or equation; value is boolean (`true` or `false`), or else [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v2.7.2]
one of `letter`, `symbol`, `formula`, `equation`.

**Comment by opoudjis** [comment]
@ronaldtse I have no idea what your objection is here, and I am  ignoring it unless you can clarify it. 

You just said a week ago that you wanted formulas and equations included as designations, because ISO TBX does. For you to turn around, after I have just implemented it, and tell me that now you don't want it, is vexatious. (I'm censoring what I actually think of it.) You have had a full year to clarify this issue. Stop getting in my way.
