### ISSUE TITLE
cannot load such file -- relaton-cli

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-standoc#70]
https://travis-ci.org/metanorma/metanorma-standoc/jobs/534781484

**Comment by ronaldtse** [comment]
@CAMOBAP795 we should refactor away `relaton-cli`? There's no way that Metanorma StanDoc needs a Relaton CLI...

**Comment by opoudjis** [comment]
PLEASE HOLD YOUR HORSES. 

This code is under refactoring. And @ronaldtse, I've already discussed this with you.

The code that processes bibliographies in Asciidoctor is currently in relaton-cli: it is the Relaton YAML code. 

Eventually, after the relaton model refactoring is complete, relaton-cli will also need to be refactored so that that code moves to the relaton gem.  That's not going to be earlier than a fortnight from now. The YAML code will also need to be changed extensively.

Until that time, LEAVE THAT DEPENDENCY ALONE. You've taken it out once already, Ronald, and I've had to put it back in.

**Comment by opoudjis** [comment]
relaton-cli is a dependency in the currently pushed version of metanorma-standoc. I can see it in the gemspec.

Travis always breaks when the code is in flux, which is almost all the time between releases. In this instance, I think it's because the published relaton-cli has not yet been exposed as an external library.

Until such time as there is a Travis job which grabs all the latest versions of gems from github, Travis is going to keep breaking between releases.

**Comment by opoudjis** [comment]
... You'll need to let me know the context of this ticket, @CAMOBAP795, but I think you're simply going to have to wait until @andrew2net is finished with the relaton gems. I can take the Asciibib functionality out of metanorma-standoc, but that's patching a specific issue, and we have a global problem with code instability between releases.

**Comment by CAMOBAP795** [comment]
@opoudjis thanks for the clarification, I just reported it not actions on my side was started

@opoudjis is it makes sense to keep this ticket or should we close it in favor of some another task?

**Comment by opoudjis** [comment]
... I can exceptionally release relaton-cli early. I don't want to. @CAMOBAP795, can you temporarily change the Gemfile of metanorma-standoc to read relaton-cli from github instead?

**Comment by CAMOBAP795** [comment]
@opoudjis no exceptional release need, I already use local gems

Just one question why we merge such incomplete features in master, according to best practices they should be in a separate feature branch and merged only if they 100% safe and stable, isn't it?

**Comment by ronaldtse** [comment]
@CAMOBAP795 I agree with you. The problem is it is hard to refer to all the in-development gems during testing; the gems need to be released in a synchronous way.

For example, if the base class has changed (base gem), all the inheriting classes (other gems) need to change too.

Do you have a good idea for this?

**Comment by CAMOBAP795** [comment]
@ronaldtse In my opinion [`git-flow`](https://danielkummer.github.io/git-flow-cheatsheet/) is a key to solve this

#### How can we use it?

Let's imagine that we need to implement some feature `A` across modules `W`, `Y`, `X`, `Z`. Dependency tree is
```
W -> X -> Z
  \
   +-> Y
```


From point of view `git-flow` we need to:
1. Create a new branch in `feature/A` for each module: `Y`, `X`, `Z`
2. Do development to not break CI we can use `Gemfile` changes (example for module `W`):
    ```
    gem 'X', :git => 'https://github.com/metanorma/X.git', :branch => 'feature/A'
    gem 'Y', :git => 'https://github.com/metanorma/Y.git', :branch => 'feature/A'
    ```

In this case, we will not break CI and both:
 - `master` (stable)
 - `feature/A` (feature) 

Will work

@ronaldtse @opoudjis let me know what do you think about this

**Comment by ronaldtse** [comment]
@CAMOBAP795 it is reasonable, we've discussed this before, but for step 2, in order to merge into master, we need to change Gemfiles for all involved gems.

**Comment by CAMOBAP795** [comment]
> in order to merge into master, we need to change Gemfiles for all involved gems. And that is very cumbersome.

In my opinion, this is the only way. Before merging some gem to master you need to make sure that you are released all dependent gem first, and this will allow us to keep master stable

**Comment by ronaldtse** [comment]
@CAMOBAP795 this arrangement implies some flow like this:

1. Get all gems in `feature/A` working 
2. Assuming the base gems don't need other gems, merge `feature/A`, then build and push those first
3. For the dependent gems, update the Gemfile, merge `feature/A`, then build and push.

@opoudjis does this work with you?

**Comment by opoudjis** [comment]
Given how much I'm working on at the same time, I will not doing separate feature branches for every ticket, and updating Gemfile 3 times a day for each gem, and merge 5 branches across a dozen gems for each release. No way. 

The only thing I can do is a dev branch and a master branch for each gem.

**Comment by CAMOBAP795** [comment]
> Given how much I'm working on at the same time, I will not doing separate feature branches for every ticket, and updating Gemfile 3 times a day for each gem, and merge 5 branches across a dozen gems for each release. No way.

This is a price of stability, no one says that it's easy and I understand your point

> The only thing I can do is a dev branch and a master branch for each gem.

This is much much better then not do them at all, and will allow us to have stable master (or more stable then now)

**Comment by ronaldtse** [comment]
@CAMOBAP795 I spoke with @opoudjis and he's OK with this: https://github.com/metanorma/metanorma-release/issues/1

Can you help us with it? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sure

**Comment by CAMOBAP795** [comment]
Resolved a while ago
