### ISSUE TITLE
Bibliography: `span` notation for online sources

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#714]
Span notation doesn't support online sources as bibliography entries in terms of having specific attributes to define accessed/cited date and to note that the source is online ("Available from World Wide Web"). Should we also support these?

Example from ISO 10303-21:
````
* [[[guid,Globally Unique IDentifier (GUID)]]], _2.5.5 Globally Unique Identifiers (GUIDs)_, [cited 2013-01-17], Available from World Wide Web, http://msdn.microsoft.com/en-us/library/cc246025.aspx
````

**Comment by opoudjis** [comment]
This is an argument I am currently having with @ronaldtse in https://github.com/metanorma/metanorma-iso/issues/884

Standards in ISO, in my understanding, do NOT permit accessed dates or URIs. 

Other bibliographic types do already support what you ask (and I can extend that to standards if I agree to  https://github.com/metanorma/metanorma-iso/issues/884, which I currently do not): `date.accessed[]`, and `uri:[]`. (We can suffix date types to date in that way.)

"Available from World Wide Web" is, as far as I am concerned, ad hoc wording which I shall NOT support. If resources are available online, that shall be indicated by providing a URI, and introductory text (which for ISO is "Available from"). 

If the source ISO document has used wording as antiquated as "Available from World Wide Web" (what is this, 1996?), and if it is mandatory to replicate it, then we should not be semantically annotating it at all (since the aim of that is to produce automatically generated, consistent rendering), we should just replicate the citation as text. 

So:

````
* [[[guid,Globally Unique IDentifier (GUID)]]], span:title[2.5.5 Globally Unique Identifiers (GUIDs)], span:date.accessed[2013-01-17], Available from World Wide Web, span:uri[http://msdn.microsoft.com/en-us/library/cc246025.aspx] span:type[booklet]
````

right now generates:

````
<formattedref><em>2.5.5 Globally Unique Identifiers (GUIDs)</em>. n.p.: n.d. Available from: <span class="biburl"><link target="http://msdn.microsoft.com/en-us/library/cc246025.aspx">http://msdn.microsoft.com/en-us/library/cc246025.aspx</link></span>.</formattedref>
````

n.p. and n.d. because we expect to see Publisher and Date in books (and booklets)—and in fact, in all bibliographic types other than standards (which get away with that only because they are liable to be updated, and have identifiers, and because ISO said so.)

IMO, this ticket should be closed, because (a) I do support "available from URI" and access dates, and (b) I think insisting on dates and publishers for non-standards is the right thing to do, no matter what ISO practice has been to date. If you disagree, feel free to reopen :)
