### ISSUE TITLE
No-label-processed error in tables inside EXAMPLE blocks

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#719]
This markup generates "No label has been processed..." error in the table cross-reference:
```adoc
====
* Definition: data,11,0,type,2,area,3,class
* Maximum dimension 1 is 5.7 in this case. See <<tab_1>>.

[[tab_1]]
.Data
|===
| 0 | 1 | 2 | 3 | ... | 11
| 6192Y | 2 x 2.5 | 2.5 | 1  | ... | 5.1 
| 6192Y | 2 x 4 | 4 | 2 | ... | 5.7
| 6192Y | 2 x 6 | 6 | 2 | ... | 6.4
|===
====
```

Error message:
````
No label has been processed for ID tab_1
````

**Comment by opoudjis** [comment]
And indeed, the fact that the table is nested inside the example is preventing a cross-reference from being generated, because my assumption is that the table is not going to be numbered independently of the example. So:

* Should the table be numbered as Example m? As Table m? Or as Example m, Table m?

@ronaldtse @manuelfuenmayor @anermina Opinions? I don't think this is a typical scenario foreseen by SDOs, and you can make a case for all three. 

I would be reluctant to add a table caption inside the example though, and independently numbered of the example. IMO the example comes first.

**Comment by ronaldtse** [comment]
I have encountered this issue before in real documents.

> Should the table be numbered as Example m? As Table m? Or as Example m, Table m?

This question can be asked in another direction.

Practically there are only 2 options:
1. Flatten the embedded numbered elements so that they are moved outside the Example.
2. Allow embedding of numbered elements within the Example. 

Normally, ISO goes with 1. This means that the table can only be "Table m".

If we go with 2, it has to be "Example m, Table x" where x is either a global (standard-wide) or local (container-wide) number.

(For the sake of completeness, I don't see how referencing a table with "Example m" can be correct.)

**Comment by manuelfuenmayor** [comment]
I have found that ISO 10303-50 may have an instance of this case:

![example1](https://user-images.githubusercontent.com/33627611/208697388-0c217aa9-ee9b-4901-9d29-7d07fa5c644d.PNG)


Now, I said "may" because I'm not sure if the table that is referenced in the example is actually part of the EXAMPLE block.
But the numbering format matches with the first option that @ronaldtse presented above.

In markup, the table was embedded into the EXAMPLE block:

```adoc
[example]
====
Consider the twelve subscript tuples for a 2 by 2 by 3 table indexed from 1. <<table2>> shows the two linear orderings of these triples indicated by values *by_rows* and *by_columns*.

[[table2]]
.Orderings indicated by ordering_type
|===
^.^h| Ordinal ^.^h| by_rows ^.^h| by_columns

^.^| 1 ^.^| [1,1,1] ^.^| [1,1,1]
^.^| 2 ^.^| [1,1,2] ^.^| [2,1,1]
^.^| 3 ^.^| [1,1,3] ^.^| [1,2,1]
^.^| 4 ^.^| [1,2,1] ^.^| [2,2,1]
^.^| 5 ^.^| [1,2,2] ^.^| [1,1,2]
^.^| 6 ^.^| [1,2,3] ^.^| [2,1,2]
^.^| 7 ^.^| [2,1,1] ^.^| [1,2,2]
^.^| 8 ^.^| [2,1,2] ^.^| [2,2,2]
^.^| 9 ^.^| [2,1,3] ^.^| [1,1,3]
^.^| 10 ^.^| [2,2,1] ^.^| [2,1,3]
^.^| 11 ^.^| [2,2,2] ^.^| [1,2,3]
^.^| 12 ^.^| [2,2,3] ^.^| [2,2,3]

|===

====

```

Maybe I should move the table outside of the example block?

**Comment by anermina** [comment]
I strongly support the first option in cases like this.
> Flatten the embedded numbered elements so that they are moved outside the Example.

**Comment by opoudjis** [comment]
I will go with:

* Warning if an asset contains another asset
* Local numbering: Example n, Table 1, 2 3
* No numbering  if there is only one of the asset inside another asset.

The assets that can contain other assets are: examples, requirements/recommendations/permissions, tables, figures. I'm going to rule out tables as making my head hurt, and requirements/recommendations/permissions as hostage to modspec; I will implement this for just examples and figures.

**Comment by opoudjis** [comment]
... This... is a large amount of work for an edge case, so I am going to issue the warning, and then demote the container-based numbering of assets to medium priority.

**Comment by ronaldtse** [comment]
> No numbering if there is only one of the asset inside another asset.

Can you clarify what this exactly means and what behavior this entails?

> The assets that can contain other assets are: examples, requirements/recommendations/permissions, tables, figures. I'm going to rule out tables as making my head hurt, and requirements/recommendations/permissions as hostage to modspec; I will implement this for just examples and figures.

I also do not understand what this means. What does "rule out tables" mean? Such that assets cannot belong within tables? Or assets cannot contain tables?

**Comment by opoudjis** [comment]
Sigh...

> No numbering if there is only one of the asset inside another asset.

If an Example contains just one Table, the label will not be "Example n, Table 1", but "Example n, Table". 

> What does "rule out tables" mean? Such that assets cannot belong within tables? Or assets cannot contain tables?

Properly, I do not believe ANY asset belongs inside any other asset to begin with. While it is *theoretically* possible for tables to contain examples, recommendations, figures, etc, (1) attempting to render them is going to either break or compromise our existing conversion tools (especially Word); (2) data entry in Asciidoc of them is going to be horrible; (3) I don't even know how numbering such embedded assets would work. I'd rather we just disallow them outright. Notes are an exception, since table notes are appended after the table proper.

**Comment by opoudjis** [comment]
We've agreed that, for now, we will outright crash when we see an asset embedded within another asset (with an appropriate error message.) Most if not all SDOs do not want to see this kind of nesting of assets to begin with, and would treat this as an error to be fixed in markup. We will eventually have to deal with this issue in  a flavour that expressly allows them, or else in a legacy document that we can't alter; we will defer implementing the rest of this ticket until it does come up.

**Comment by opoudjis** [comment]
So @manuelfuenmayor Right now, I'm going to abort execution with that example, and urge you to move the table outside the example. I'll need some persuading to actually implement this. The implementation of crossreference could in fact be "Example 3, Table" outside of the example, and "Table" within the example; but in general, this is markup that we should be avoiding.

**Comment by manuelfuenmayor** [comment]
Markup changes applied. Table was moved outside the example block.

**Comment by opoudjis** [comment]
Relaxing refusal to number example/table, per https://github.com/metanorma/mn-samples-itu/issues/159 : we have already issued the pertinent warning.
