### ISSUE TITLE
`Huge input lookup` error

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#720]
When a document includes figures that are too big in size (about 7 MB in total), build crashes with the following error:

````
Malformed Output XML for html: 1198:62827: FATAL: internal error: Huge input lookup
````

**Comment by opoudjis** [comment]
@anermina could you point me to a document so I can replicate this?

**Comment by anermina** [comment]
@opoudjis the issue appeared while I was converting the following document: https://github.com/metanorma/scc-smart-documentation/tree/main/sources/smart-mmel-modeling-methodology (originally https://github.com/metanorma/scc-smart-documentation/blob/main/smart-mmel-modeling-methodology.pptx). The size of several images has been reduced in order to avoid crashing. I believe the problem can be reproduced by including one more image (cca. 200 KB in size) in the main document.

**Comment by opoudjis** [comment]
I think the issue is that we are (a) insisting on data URI encoding images, so that they are embedded in the XML, and (b) that we are doing so inside XML attributes, not XML elements. XML attributes do indeed have a size limit, and it likely is 6 MB.

If it's that I will need to experiment to see what the workaround here is; it may simply be a matter of 

(a) putting the data URI encoded image inside an element instead of an attribute value, and then generating HTML without data URI encoding (since HTML does require it to be an attribute), or
(b) disabling data URI encoding if any image is over 6 MB.

.... If that is the issue. You are talking about lots of smaller images through, and a 200 KB image on its own should not trigger the maximum size of an XML attribute.

So, I don't know what the issue is yet, but I do know where to look.

**Comment by opoudjis** [comment]
@ronaldtse I cannot access https://github.com/metanorma/scc-smart-documentation/

**Comment by opoudjis** [comment]
Replicated for a 20MB JPEG I had lying around:

> Malformed Output XML for html: 348:69: ERROR: xmlSAX2Characters: huge text node (see a.html.err)

This indicates that the error is not happening in Nokogiri *encoding* the Data URI (it would have already failed in the Semantic XML if so), nor even in generating the image code in HTML, but in postprocessing, when I parse the XML file for postprocessing and manipulation, instead of just building it.

The issue goes away if I parse the XML file in Huge mode.

The question then becomes, is it a good idea to have 20MB-long attribute values.

**Comment by opoudjis** [comment]
20 MB image works in a test document, for Safari, Chrome, Firefox, PDF (though shrunk quite small!), and DOC.

The information online, that Chrome sets a limit on data URIs of 2MB, is dated (2017). From https://caniuse.com/?search=data%20URI, the only limit is 4GB, and even that is on Edge up to 2018.
