### ISSUE TITLE
`initials` and `givenname` related to one `surname` cause crash in `span` notation

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#721]
It seems that Metanorma currently assumes that `surname` can be related to either `givenname` or `initials` in the `span` notation for bibliographic entries. However, some citation styles include both initials and given names (for authors with a middle name).

Therefore, following encoding causes a crash with the message `Missing surname: issue with bibliographic markup in "<em>The Navigation Surface: A New Database Approach to Creating Multiple Products from High-Density Surveys</em>": {:role=>"author", :entity=>"person", :givenname=>"Andy"}`.
````
* [[[NavigationSurface,The Navigation Surface]]],
span:surname[Smith], span:givenname[Shep] span:initials[M. LT];
span:surname[Alexander], span:givenname[Lee]; and
span:surname[Armstrong], span:givenname[Andy],
"span:title[_The Navigation Surface: A New Database Approach to Creating Multiple Products from High-Density Surveys_]" (span:date[2002]).
span:publisher[International Hydrographic Review].
span:uri[http://scholars.unh.edu/ccom/976]
````

In order to avoid crash, initials need to be combined with the given name, i.e.:
````
* [[[NavigationSurface,The Navigation Surface]]],
span:surname[Smith], span:givenname[Shep M. LT];
span:surname[Alexander], span:givenname[Lee]; and
span:surname[Armstrong], span:givenname[Andy],
"span:title[_The Navigation Surface: A New Database Approach to Creating Multiple Products from High-Density Surveys_]" (span:date[2002]).
span:publisher[International Hydrographic Review].
span:uri[http://scholars.unh.edu/ccom/976]
````

Entry from the source document:
![image](https://user-images.githubusercontent.com/55683568/208531979-69d3950f-070c-4a8e-b9e3-8cc27224a6e4.png)

Is it possible to allow both initials and given name to be related to one surname, or to relax this condition so that it produces a warning instead of crashing?

**Comment by opoudjis** [comment]
> Is it possible to allow both initials and given name to be related to one surname, or to relax this condition so that it produces a warning instead of crashing?

I'll change the internal encoding to take care of this.

Initials, the way they currently are provided for in relaton, are meant to cover all given names of an author: they are mutually exclusive with `givenname:[]`. Hence the mapping to formatted-initials in relaton, to hardcode the formatting as required by IETF.

Middle name initials are currently treated as just given names inside of relaton; they are not covered by the current formatted-initials element. Rather than complicate matters further, I'm going to change the internal encoding, so that if givenname is preceded or followed by initials, I convert that initials to givenname internally.

**Comment by opoudjis** [comment]
Ok, so this is the actual problem with doing what you've requested.

surname givenname-1 givenname-2 surname

How do I know whether givenname belongs to the first name or the second name?

The current presupposition is, surname alternates with either initials or givenname, and there can only be one given name or initials associated with a surname; so (surname-1 givenname-1) (givenname-2 surname-2).

This in fact *permits* us to do surname-1 givenname-1 givenname-2 surname-2 at all.

If I'm going to abandon that presupposition, then I cannot allow (surname-1 givenname-1) (givenname-2 surname-2). All surnames and givennames must occur in the same order, so only (surname-1 givenname-1) (surname-2 givenname-2) is permitted.

I think that's actually fine. The rendering of any text containing spans is discarded, and rebuilt with relaton-render; so there is no reason to enter names as surname-1 givenname-1 givenname-2 surname-2 at all. And the flexibility of marking up multiple given names, or given name + initials combinations, is worthwhile.

@ReesePlews notifying you of this as well. In future, all names must be given as surname:[] followed by one or more of givenname:[] or initials:[]

**Comment by ReesePlews** [comment]
@opoudjis thank you for the alert on this.  if i presently have 
`surname givenname-1 givenname-2 surname`
in the ieee document bibliography then i have made a mistake because i knew they should be "surname" "given_name" however sometimes i could only find initials for given name, so i tried to add them as such. i will go back through and check.
i cannot advise on the other comments. i will follow the documentation on what is required once it has been decided. thank you.

**Comment by opoudjis** [comment]
We actually won't differentiate in the underlying processing between initials and given name: we will render what we find, so no need to fret about that.

**Comment by ReesePlews** [comment]
@opoudjis thank you, if there are any issues, i will report them.
