### ISSUE TITLE
Adoption: referencing an embedded document (e.g. PD ISO/TR 44000)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#749]
(From https://github.com/metanorma/mn-samples-bsi/issues/243)

In PD ISO/TR 44000:2019, it includes a foreword that says:

`sources/pd-iso-tr-44000/sections/pd-00-foreword.adoc`:
```adoc
== National foreword

This Published Document is the UK implementation of
<<ISO_TR_44000_2019,ISO/TR 44000:2019>>.
```

The document `ISO/TR 44000:2019` is exactly the document that is being embedded:

```adoc
:adopted-from: ISO/TR 44000:2019
...
embed::iso-tr-44000.adoc[]
```

We need to make the embedded document available for citation in the adopting document.

This issue is related to [metanorma-bsi#](https://github.com/metanorma/metanorma-standoc/issues/746)

Since it is necessary to define the anchor for the embedded document anyway, we could potentially use one of:
```adoc
embed::iso-tr-44000.adoc[anchor=ISO_TR_44000_2019]
```

or

```adoc
[[ISO_TR_44000_2019]]
embed::iso-tr-44000.adoc[]
```

**Comment by opoudjis** [comment]
We have the docidentifier of the immediately embedded document, as `bibdata/relation[@type = 'derivedFrom']/bibitem/docidentifier`. So we do not need to reenter that.

We do not need to reenter the citation of the embedded document, since by default we are not rendering references of the embedding document separately from the embedded document. (And if we do, we would indeed expect the embedded document to be cited explicitly.)

So Three goes away.

One becomes the requirement that, for

````
<<id>>

[[id]]
embed::doc.adoc[]
````

<<id>> (if possible) is populated with the docidentifier of the embedded doc, while hyperlinking to the first available point in the embedded doc. (It may be expedient to make it a bookmark, rather than the identifier of an existing element.)

Two would be needed if there were clauses in the embedding document distinct from the embedded document, and it would involve some sort of hierarchical processing of anchors, and conditional prefixing of them with document identifiers, as with cross-references within a collection. But I am hopeful we can avoid that.

**Comment by ronaldtse** [comment]
It does seem that it may be better implemented as part of the Collection functionality. Right now our collection does not support this use case.

**Comment by opoudjis** [comment]
I'll do this for the simple use case of minimal content (forewords) in the embedding document, which is a recurring use case. If there is a lot more, and there is a real document on the embedding side interacting with crossreferences to the embedded document—i.e. if requirement Two is a substantial thing, then yes, this should be addressed with collections instead.
