### ISSUE TITLE
Force specific position of the limits for sum, product, integral, etc.

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#763]
ISO 80000-2 demonstrates different versions of the same entry for some math expressions, e.g.:
![image](https://user-images.githubusercontent.com/55683568/227384038-e48d9a79-3484-46f3-be8e-4c96417a49ec.png)

The limits are currently automatically generated by Metanorma as follows:
HTML:
![image](https://user-images.githubusercontent.com/55683568/227384284-f4b5607e-70fc-4c80-b6c7-3ad03cabe9d7.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/227384119-4857db03-8f0b-4a73-9adc-14bc143f5ddb.png)

Could we enable forcing a specific position for the limits?

**Comment by opoudjis** [comment]
For limits and similar underscripts and overscripts in MathML (HTML), the global attribute `displaystyle=true` forces the limits to appear as expected, under and over the symbol. If `displaystyle=false`, the height of math expressions is minimised ("compact"), and they appear as subscripts and superscripts instead.

So we have a suite of problems:

1. The displaystyle default of Word (OOXML) is not the same as the displaystyle default of HTML (MathML)
2. The displaystyle default for both does not appear to conform to desired behaviour in MathML: that inline math expressions have compact style, displaystyle=false (so that prose does not look crap), and standalone formulas use normal style, displaystyle=true.
3. We have no way of telling AsciiMath to set the style to one or the other.

To start with (3): no. We will *not* introduce style commands to AsciiMath, they are utterly out of scope for it. The correct markup for the "are also used" line is to use MathML, not AsciiMath, to differentiate the two rendering styles. There are things that AsciiMath cannot and should not do, and this is one of them. So not:

````
stem:[nnn_{i in I}^n], stem:[nnn_{i in I}] and stem:[nnn_{i in I}] 
````

but 


````
stem:[<math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="false"><msubsup><mo>⋂</mo><mrow><mi>i</mi><mo>∈</mo><mi>I</mi></mrow><mi>n</mi></msubsup></mstyle></math>], stem:[<math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"><munder><mo>⋂</mo><mrow><mi>i</mi><mo>∈</mo><mi>I</mi></mrow></munder></mstyle></math>] and stem:[<math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="false"><munder><mo>⋂</mo><mrow><mi>i</mi><mo>∈</mo><mi>I</mi></mrow></munder></mstyle></math>] 
````

(You get the MathML by converting a doc with the AsciiMath, and looking at the Semantic XML.)

**Comment by opoudjis** [comment]
There is also a bug in Plurimath. The munderover operands, sum prod ^^^ vvv nnn uuu, are being rendered with msubsup, which means they can never be rendered with limits above and below. This is a big: they should be rendered with munderover (or munder or mover, if an operand is missing). Whether munderover is rendered in normal or compact style is determined by the displaystyle operand.

**Comment by opoudjis** [comment]
There remains the issue that DOC and HTML defaults are inconsistent. That is the result of two separate bugs:

* The conversion to OOXML is ignoring the displaystyle attribute in MathML, and is deciding whether to do compact or normal rendering based on other criteria that I haven't worked out yet. Debugging this will involve debugging the XSLT provided by Microsoft.

* Plurimath is defaulting to displaystyle="true" universally in its output. Not too concerned about that, I can switch the displaystyle value locally after conversion, based on context.

**Comment by suleman-uzair** [comment]
@opoudjis 

> you are converting **Plurimath** to **OMML**; is that code ready for use?

I am currently testing it, will let you know once it is finalized.
> please confirm that it respects the **displaystyle** attribute, or allows me to invoke it

**Plurimath** currently sets the **displaystyle** attribute by default to true. I will make the necessary code updates in a new pull request to provide an option for users to invoke the **displaystyle** attribute as needed.

**Comment by opoudjis** [comment]
Changing Metanorma XML model to pass in mandatory `block` attribute, about whether element should be rendered as if a block or as if an inline element. (Currently it is contextually determined, but we cannot rule out user override.)

**Comment by opoudjis** [comment]
As part of refactor, I need to know when Asciimath is to be converted to MathML whether it is displaystyle or not. I have allowed a text-based asciimath conversion in Html2Doc for Word docs, because the Word XML is not necessarily clean XML, and shouldn't go into Nokogiri. But Html2Doc has not received raw AsciiMath in years, all maths is converted to MathML in Semantic Metanorma XML. So that code needs to move into metanorma-standoc, and should not be triggered within html2doc.

**Comment by opoudjis** [comment]
Input:

````
stem:[nnn_{i in I}^n]

[stem]
++++
nnn_{i in I}^n
++++
````

HTML is ok:

<img width="483" alt="Screenshot 2023-08-03 at 21 47 53" src="https://github.com/metanorma/metanorma-standoc/assets/1911039/21e79b50-f9f6-40a3-bd82-306754d7b5cb">

PDF is ok:

<img width="900" alt="Screenshot 2023-08-03 at 21 58 04" src="https://github.com/metanorma/metanorma-standoc/assets/1911039/6419fead-5efc-46ea-b844-9357dc2899e7">


DOC is very far from OK:

````
<img width="833" alt="Screenshot 2023-08-03 at 21 49 57" src="https://github.com/metanorma/metanorma-standoc/assets/1911039/ba5ac06c-8dce-4542-b896-76749859a958">
````

and that is pending https://github.com/plurimath/plurimath/issues/173 (among other tickets, some of which may not yet have been authored.)

Putting this ticket on hold, pending DOC resolution.

**Comment by opoudjis** [comment]
No, will use ticket https://github.com/metanorma/metanorma-standoc/issues/796 instead to cover the failure of DOC to pay attention to displaystyle.
