### ISSUE TITLE
(URGENT) Duplicated "preferred term" shown when defined twice

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#797]
```
=== integral shape element
preferred:[integral shape element]
alt:[integral feature]

portion of the shape that lies entirely on the surface of the shape
```

This will get rendered twice, like this:
<img width="452" alt="Screenshot 2023-07-08 at 8 55 48 AM" src="https://github.com/metanorma/metanorma-standoc/assets/11865/6f20015b-f2f9-4a6a-a643-f08700af604b">

**Comment by opoudjis** [comment]
As far as I am concerned, this is a markup error: the preferred term is read in from the term heading, and any additional instances of `preferred:[ ]` are meant to be synonyms, not random duplicates of the term. This is not a bug, this is bad markup, and documentation is very clear on the expected behaviour. https://www.metanorma.org/author/topics/document-format/section-terms/#preferred-designations :

> The first preferred designation is specified as a section heading under the “Terms and definitions” clause.

> The preferred:[…​] command can be used to specify additional designations for the second and subsequent designations.

**Comment by ronaldtse** [comment]
> As far as I am concerned, this is a markup error: the preferred term is read in from the term heading, and any additional instances of preferred:[ ] are meant to be synonyms, not random duplicates of the term. This is not a bug, this is bad markup, and documentation is very clear on the expected behaviour

I quite disagree here, being the user that encountered this myself. If I write that line 3 times I get 3 synonyms? That's very strange.

**Comment by opoudjis** [comment]
@ronaldtse Why on earth would you write that line 3 times to begin with?! What next, write the same clause heading three times and expect me to conflate them?

This is perverse, it contravenes very clear documentation, and it is DECIDEDLY not urgent.

**Comment by ronaldtse** [comment]
Because the terms are generated from a liquid template.

```liquid
{% assign eng = concept.eng %}

{% assign preferred_designations = eng.terms | where: "normative_status", "preferred" %}
{% assign first_des = preferred_designations.first.designation %}

{% if first_des %}
==== {{ first_des }}
{% else %}
==== NO PREFERRED DESIGNATION FOUND: {{ concept.term }}
{% endif %}

{% if eng.domain %}
domain:[{{ eng.domain }}]
{% endif %}

{% if eng.terms.size > 1 %}
{% for term in eng.terms %}
{% if term.designation == first_des %}{% continue %}{% endif %}
{{ term.normative_status }}:[{{ term.designation }}]
{% endfor %}
{% endif %}

{{ eng.definition[0].content }}
```

Notice this code:
```liquid
{% assign preferred_designations = eng.terms | where: "normative_status", "preferred" %}
{% assign first_des = preferred_designations.first.designation %}

...

{% if eng.terms.size > 1 %}
{% for term in eng.terms %}
{% if term.designation == first_des %}{% continue %}{% endif %}
{{ term.normative_status }}:[{{ term.designation }}]
{% endfor %}
{% endif %}
```

If we can support multiple `preferred:[...]`, then this line can be removed:

```liquid
{% if term.designation == first_des %}{% continue %}{% endif %}
```

And in any case, showing multiple identical preferred terms is wrong?

**Comment by opoudjis** [comment]
> Because the terms are generated from a liquid template.

Then debug your Liquid template. Which you already have. Having me introduce complications in my code because you want to allow buggy Liquid code is buggy is wasting my time.

> And in any case, showing multiple identical preferred terms is wrong?

*MARKING UP* identical preferred items is wrong to begin with. As I already said, am I to start looking for duplicate clauses too?

I'm implementing this ticket anyway (because I'm about to crash Metanorma if there are duplicate preferred terms in markup), but my resentment at having my time wasted remains. My time is limited, and this is not how to use it.
