### ISSUE TITLE
Discrete section misplaced at the beginning of the document

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#815]
Source: https://github.com/metanorma/mn-samples-bsi/pull/304

First discrete section is getting placed before the main title of the document.
Markup:
```adoc
== Foreword
...

[[section1]]
[discrete%section]
== Presentation and typography

[NOTE,type=commentary,target=section1]
====
This section is applicable largely to typeset documents, i.e. PDFs
or printed documents. Some elements will not be relevant to online
documentation, e.g. the placing of footnotes and guidance relating
to continuation of figures and tables.
====

[[sec_1]]
== General

Typeset standards are normally printed on A4 pages, using a set layout
and typically using colour to pick out specific elements of text...
````

Output:
![issue2-html](https://github.com/metanorma/metanorma-standoc/assets/33627611/9bf6fd0b-8961-41f1-911b-ec272d59b119)

Original:
![issue2-original](https://github.com/metanorma/metanorma-standoc/assets/33627611/c8392132-1820-4ab4-baba-218fda17c162)

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you provide a screenshot of the original document too, for completeness of the issue?

**Comment by manuelfuenmayor** [comment]
Done

**Comment by Intelligent2013** [comment]
@opoudjis FYI, https://github.com/metanorma/metanorma-bsi/issues/441#issuecomment-1722489499

**Comment by opoudjis** [comment]
The markup is:

````
[[section1]]
[discrete%section]
== Presentation and typography

[NOTE,type=commentary,target=section1]
====
This section is applicable largely to typeset documents, i.e. PDFs
or printed documents. Some elements will not be relevant to online
documentation, e.g. the placing of footnotes and guidance relating
to continuation of figures and tables.
====

[[sec_1]]
== General

...
````

If you put just the floating title on its own in that position, it will attach to the sections correctly.

If you put just the note on its own in that position, it won't: it will attach to the preceding preface.

And that's because https://www.metanorma.org/author/topics/document-format/text/#admonitions : you need to insert `[beforeclauses=true]` on that note

But that's not enough. If a beforeclause note appears in the main body of text, it will be moved to before the first clause, and if a beforeclause note appears in the preface, it will be moved to before the start of the preface. So:

* Scope Title (start of main body of document)
* Beforeclause note
* Scope content

What we have here is

* Floating title
* Beforeclause note
* Scope Title 
* Scope content

And Metanorma doesn't realise that the floating title is supposed to already be the start of the main body of the document. It gets sufficiently confused by the combination of floating title and note, that it leaves both of them in the preface.

I will make the second case work, but dealing with constant exceptions like this is why Metanorma is unmanageable.

**Comment by opoudjis** [comment]
I've got it working, but now the Middle Title in the HTML (the title at the start of the main body) is occurring after the floating title...
