### ISSUE TITLE
Include the word "through" as a locality range in cross-references

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#820]
In [ISO 19111:2007](https://github.com/metanorma/iso-19111), there are several instances of xref ranges that use the word "through". For example,

![capture1](https://github.com/metanorma/metanorma-standoc/assets/33627611/fa4ae1cc-fcf9-448e-a599-d8eb395b08f6)

Maybe we should add this word as new range locality so that the markup would be, for example: `<<table33;through!table41>>`.
(Or should I use the word `to` instead?)

**Comment by opoudjis** [comment]
Use "to" for now. My inclination is to make that a configurable option. It means the same thing as "to", and it's properly speaking an i18n issue. 

How urgent is this to "get right" in presentation? @ronaldtse ?

**Comment by opoudjis** [comment]
Strictly speaking, i18n is already configurable, by adding a yaml file with local options to override those in the flavour's YAML. So you can implement a workaround right now:

Document:

`:i18nyaml: my.yaml`

my.yaml:

`chain_to: "%1 through %2"`

(The built in value is of course "%1 to %2". "chain", because it can be used in a sequence of connectives forming a chain of "to" expressions, and I can't assume that all languages are going to behave the same way: "1 to 4, 7 to 9, and 12 to 14".)

What I'm considering doing here is also adding such changes as document attributes, if there's only going to be one or two.

**Comment by manuelfuenmayor** [comment]
> Strictly speaking, i18n is already configurable, by adding a yaml file with local options to override those in the flavour's YAML. So you can implement a workaround right now:

When I try this workaround, I get `Fatal Error: No such file or directory @ rb_sysopen - my.yaml`
In addition, I'm sure if Ronald would approve this solution.
I'm using `to` in the meantime.

**Comment by opoudjis** [comment]
> I mean, the document uses both words "to" and "through".

... I refuse to action this. This is automated formatting. If the document is going to randomly change the rendering of ranges from one instance to the next, then we should not be automating the formatting at all. I am not going to replicate errors.

If you don't want consistent rendering of ranges, then do it the old-fashioned way, `<<x>> through <<y>>`.

**Comment by ronaldtse** [comment]
I wonder if we can allow this. The ISO House Style and the ISO DIR 2 both do not specify language for the references to a range of elements.

**Comment by opoudjis** [comment]
This is not an ISO house style issue, it is a Metanorma consistency issue. We are not editing Word documents. We cannot proliferate an open-ended class of !connectives; internationalisation alone will become unmanageable because of it.
