### ISSUE TITLE
Turn off substitution for quotation mark and apostrophe 

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#827]
Source issue: https://github.com/metanorma/pdfa-iso-32000-2/issues/11#issuecomment-1802197393

Metanorma substitutes smart quote characters for quotation mark and apostrophe:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/0c28a51e-f788-4b48-a7e0-c76e98f326c5)
(from https://www.metanorma.org/author/topics/document-format/text/#character-substitutions)

In the https://github.com/metanorma/pdfa-iso-32000-2/issues/11 we need to use the glyphs from the old font `D050000L` with codes:
- `0x0022`:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/7aa297a9-252f-443d-b2b1-3ca244558ad5)

- `0x0027`:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/0f7b25d6-bfd7-4c5e-9076-9219a0d36a5e)

In the presentation XML these chars replaced by `0x201c`:
```xml
<span style="font-family:&quot;D050000L&quot;">“</span>
```
and `0x2018`:
```xml
<span style="font-family:&quot;D050000L&quot;">‘</span>
```
which are missing in `D050000L`.

Question: is there possibility to turn-off the AsciiDoc characters substitutions for `0x0022` (quotation mark) and `0x0027` (apostrophe)?

**Comment by opoudjis** [comment]
These are not in fact turned to character substitutions by Asciidoctor,  but in postprocessing, since a smartquotes module we manage and apply contextually is more reliable.

Right now, the following inline markup is exempt from smart quotes:


* ++"++

* \`"`

* pass-format:xml["]

Monospace is not what you want here. The `++` pass macro will end up resolved in Metanorma, and will still be subject to smart quotes in postprocessing.

As it turns out though, pass-format:[] is what you want: we're explicitly telling Metanorma not to process the characters it contains, and to leave them to be dealt with downstream, in specific outputs. We never do, so they are left alone throughout the processing chain.

So

````
[css font-family: "Code 2000"]#pass-format:xml["]#
````

works right now.

(Nesting macros in Asciidoctor is a nightmare, but lucky for you, you don't need that right now.)

**Comment by opoudjis** [comment]
Actually, pass-format:xml is bogus. The format is meant to be all supported formats, and if you see `<passthrough format="xxx">` where xxx does not include pdf, you are meant to ignore it. Implementing `<passthrough format="all">`, which is valid in all downstream formats.

**Comment by Intelligent2013** [comment]
@opoudjis thank you, `pass-format:xml["]` solved the issue.

**Comment by opoudjis** [comment]
Update: I am going to do the processing of passthrough in preprocessing of Presentation XML, before passing it to you, @Intelligent2013, so you should never end up seeing it...

**Comment by opoudjis** [comment]
No, the former comment is wrong. `passthrough` is staying.

**Comment by opoudjis** [comment]
@Intelligent2013 Use `pass-format:all["]`
