### ISSUE TITLE
Images included in pdf are not middle aligned

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#85]
Happening in https://github.com/CalConnect/csd-digital-addresses. Yes, it's the same document that @ronaldtse had provided access.

How to trigger (in case you don't know): `make`

Path of the problematic document (after compilation): "documents/cc-19160-6.pdf"

Symptoms:

- In "documents/cc-19160-6.pdf", images included are not middle aligned, e.g. Figure 1. Hopefully, you found where "Figure 1" is and I don't have to specify all the instances.

- Only happens to the pdf, but not other formats. You can try "documents/cc-19160-6.html". You name it for other formats.

Please feel free to ask if you need even more details. Thanks!

**Comment by opoudjis** [comment]
It is true that all images in HTML and therefore PDF are left aligned, unlike in Word where they are centre aligned. @ronaldtse should I make centre alignment universal, or just for PDFs? And all flavours, or just this one? This is a CSS change, but it might impact every flavor.

**Comment by ronaldtse** [comment]
@opoudjis previously all HTML images are centered. I think it's safe to center all images across flavors.

**Comment by ronaldtse** [comment]
It may be the case where HTML "appear centered" but is actually left-aligned. In this case, let's center all images anyway.

**Comment by PeterTKY** [comment]
Agree. The center-aligned captions of those images may show the original intent to center align also the images.

**Comment by opoudjis** [comment]
Will apply to all flavours and then release, likely today.

**Comment by opoudjis** [comment]
Interesting. The 100% sizing is only being applied to HTML anyway, and not PDF. It would be preferable for 100% to be applied only when the image is bigger than the current screen, not smaller. Investigating further: enlarging images just looks horrible. Investigating further.

**Comment by opoudjis** [comment]
Ok, so until now, solution was:

PDF: no special formatting to images. (So they ended up left aligned.)
HTML: width: 100%; height: auto; (So image was either blown up to 100%, or shrunk down to 100%. In either case, there was never an issue of left alignment, because the image filled the screen.

The formatting of images within figures, whether in PDF or in HTML, shall henceforth be centered, and reduced down to 100% but never enlarged past 100%:

margin-left: auto;
margin-right: auto;
display: block;
max-width: 100%;
height: auto;
