### ISSUE TITLE
Chocolatey installation failing on Windows Ruby 3.2

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#854]
* https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20293484805
* https://github.com/metanorma/metanorma-iso/actions/runs/7458642489/job/20293481457

**Comment by CAMOBAP** [comment]
Infrastructure issue on chocolatey side. A single job re-run (as on the screenshot below) resolved the issue

<img width="640" alt="Screenshot 2024-01-09 at 10 20 27 AM" src="https://github.com/metanorma/metanorma-standoc/assets/2169738/32154705-062c-42a7-9dba-0828438fba56">

Passed re-runs:
- https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20294257836
- https://github.com/metanorma/metanorma-iso/actions/runs/7458642489/job/20294035085

The release workflow failed as expected because release for those gems was done manually. So those failures can be ignored
- https://github.com/metanorma/metanorma-iso/actions/runs/7459095103/job/20294368508
