### ISSUE TITLE
Process attachments in PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#872]
Follow-on from https://github.com/metanorma/metanorma-standoc/issues/709

Attachments are now included in Presentation XML. I describe how in https://github.com/metanorma/metanorma/issues/353

The task for you is to do... something with these attachments in PDF. I don't know what or how, but @ronaldtse has said that this is expected by our clients. The PRs in metanorma-standoc and isodoc are staying draft until you have a resolution to this, but the attachments are currently treated in Presentation XML as links to assets in the attachments subfolder. The Semantic and Presentation XML retain Data URIs for the attachments, but Data URI generation for attachments is optional (though default behaviour.)

**Comment by opoudjis** [comment]
[Archive 4.zip](https://github.com/metanorma/metanorma-standoc/files/14433326/Archive.4.zip)

The attached is an example of Presentation XML linking to an attachments folder.

**Comment by Intelligent2013** [comment]
From `a.presentation.xml`:
```xml
	<metanorma-extension>
		...
		<attachment name="spec_helper.rb">data:application/octet-stream;base64,cmVxdWlyZ...</attachment>
		
	</metanorma-extension>
	
	...
	<sections>
		<clause id="_cl" inline-header="false" obligation="normative" displayorder="2">
			<title depth="1">1<tab/>Cl</title>
			<p id="_ea5d9037-eb3f-8819-ce7c-2b595e4dd1c6">
				<link target="/Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iso/_a_attachments/spec_helper.rb">text</link>
			</p>
		</clause>
	</sections>
```

Tasks:
- [ ] the data from `metanorma-extension/attachment` should be included in PDF as attachments
   - [ ] if `attachment/text()` isn't empty, then decode file from base64 and attach it into PDF
   - [ ] if ``attachment/text()` is empty, then 
       - [ ] determine the current XML file name (before `.presentation.xml` if presents), and
       - [ ]  attach the file from the folder `_{filename}_attachments`
- [ ] the click on the link `<link target="/Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iso/_a_attachments/spec_helper.rb">text</link>` opens the attached file

**Comment by Intelligent2013** [comment]
If `link/@target` contains `/_{filename}_attachments/` then it means that this link points to the PDF attachment file.

**Comment by Intelligent2013** [comment]
XSLT and mn2pdf (https://github.com/metanorma/mn2pdf/releases/tag/v1.84) updated to support the attachments in the PDF.

Note: on my machine this message is showing when I tried to open the attachments:

![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/1d11613e-ada3-4f69-82fd-8ff5de8a0377)

![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/d037ba31-6682-4e5b-bd2a-c36632a5cd54)

The preferences allow to open files, but the button `Restore` isn't enabled.

Example with  `spec_helper.rb`: [a.presentation.pdf](https://github.com/metanorma/metanorma-standoc/files/14479028/a.presentation.pdf)

I've renamed the attachment to `spec_helper.txt` in the source Presentation XML and after that everything is working.
Example with `spec_helper.txt` :[a.presentation.pdf](https://github.com/metanorma/metanorma-standoc/files/14479012/a.presentation.pdf)

![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/72def685-ac14-4fb1-ae2a-940514fb7604)

When I add the attachment manually by the Acrobat:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/3ba31e04-0946-496b-987f-e0f0314d3973)

On the page https://helpx.adobe.com/acrobat/using/attachments-security-risks-reader-acrobat.html:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/ea650751-ea87-440f-8317-339b4aa07ae9)
but I didn't change the attachment defaults.

Only way to change it - via Windows registry (found here https://community.adobe.com/t5/acrobat-discussions/adobe-cannot-open-the-file-attachment-because-your-pdf-file-attachment-settings-do-not-allow/td-p/10984499 and https://www.adobe.com/devnet-docs/acrobatetk/tools/AppSec/attachments.html)
`.rb` is present in the list `tBuiltInPermList`:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/b25e3a15-25f0-4194-a7cd-b69d1762a810)

I've change to `.rb:0`:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/06a4d4ec-220a-473b-93a4-5ababf040aba)

and `spec_helper.rb` is opening now.
