### ISSUE TITLE
Inline passthrough blocks provoke compilation failure

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#913]
In relation to https://github.com/metanorma/rfc-asciidoc-rfc/issues/26

# Description
`pass` macro (like `pass:a[text]`) is causing compilation error in IETF documents. Not tested in other flavor.

# To replicate

Use this branch of rfc-asciidoc-rfc repository: https://github.com/metanorma/rfc-asciidoc-rfc/tree/test-pass-bug,
and compile the `draft-ribose-asciirfc.adoc` file. To succeed in compilation, just remove the `pass:a[]` markup from `01-intro.adoc`.

**Comment by opoudjis** [comment]
Um... no. The markup is wrong to begin with.

What you are trying to put into the output is `<<id>>`.  This needs to end up as `<tt>&lt;&lt;id&gt;&gt;</tt>`: the `<<` and `>>` must absolutely not end up as `<` in the output XML, because that would be interpreted as mangled XML itself.

And that means that the pass behaviour you want, per https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/ , is `pass:c[]`: you want the `<< >>` to be converted to `&lt;&lt; &gt;&gt;` . `pass:a[]` instead converts any instances of document attributes in braces.

You also don't want the backticks inside the macro, they belong outside:  

````
`pass:c[<<id>>]`
````

This renders correctly as: 

````
<tt>&#x3c;&#x3c;id&#x3e;&#x3e;</tt>
````

**Comment by opoudjis** [comment]
No, that's not all. The macro is being mangled when it is an include file.

`pass:c[<<id>>]`

renders as `<tt>&lt;&lt;id&gt;&gt;</tt>` at document level, but as `<tt>id</tt>` when in an included file. This will be caught up in include preprocessing.

**Comment by opoudjis** [comment]
... No, that went away. Huh.
